# Generated by Django 4.2.6 on 2023-11-18 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_taskfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='comment_attachments/')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.comment')),
            ],
        ),
    ]
