# Generated by Django 4.2 on 2023-05-11 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_project_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Awaits', 'Awaits'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Expired', 'Expired')], max_length=12),
        ),
    ]
