# Generated by Django 4.2.1 on 2023-05-29 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_category_options_alter_project_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Urgent', 'Urgent'), ('Moderate', 'Moderate'), ('Non-Urgent', 'Non-Urgent')], default='Non-Urgent', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Awaits', 'Awaits'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Expired', 'Expired')], default='Awaits', max_length=12),
        ),
    ]
