# Generated by Django 4.2.1 on 2023-06-21 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_project_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
