# Generated by Django 4.2.1 on 2023-07-18 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='outdated',
            field=models.BooleanField(default=False),
        ),
    ]
