# Generated by Django 4.2.1 on 2023-07-19 15:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_task_outdated'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='teammates',
            field=models.ManyToManyField(blank=True, related_name='teammate', to=settings.AUTH_USER_MODEL),
        ),
    ]
