# Generated by Django 4.2.6 on 2023-10-13 18:41

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_task_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='body',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
