# Generated by Django 4.2.6 on 2023-10-17 16:14

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=django_cryptography.fields.encrypt(models.TextField(default=None, null=True)),
        ),
    ]
