# Generated by Django 4.2.6 on 2023-10-19 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_comment_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, default='profiles/default_photo.jpg', null=True, upload_to='profiles/'),
        ),
    ]
