# Generated by Django 4.2.6 on 2023-10-19 09:38

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0026_user_profile_photo"),
    ]
