# Generated by Django 4.2.6 on 2023-10-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0028_remove_taskattachment_photo"),
    ]
