# Generated by Django 4.2.6 on 2023-10-19 14:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0029_rename_taskattachment_attachment_task_attachments"),
    ]
