# Generated by Django 4.2.6 on 2023-10-19 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0031_attachment_task_attachments"),
    ]
