# Generated by Django 4.2.6 on 2023-10-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_attachment_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='attachments',
            field=models.ManyToManyField(blank=True, related_name='task_attachments', to='core.attachment'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(default=None, upload_to='files/tasks/'),
            preserve_default=False,
        ),
    ]
