# Generated by Django 4.2.6 on 2023-10-19 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_task_attachments_alter_attachment_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='attachments',
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
