# Generated by Django 4.2.6 on 2023-10-19 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_remove_task_attachments_delete_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='intro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
