---
name: checks

on: [push]


jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04

    services:
      postgres:
        image: postgres:latest
        env:
          DB_USER: postgres
          DB_PASS: postgres
          DB_NAME: postgres
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test

        run: docker-compose run -e "DB_NAME=postgres" -e "DB_USER=postgres" -e "DB_PASS=postgres" --rm app sh -c "python manage.py wait_for_db && pytest"
